### ISSUE TITLE
Maybe the connection Funcs could return an error so it could be used as lib

### ISSUE THREAD

**Issue by tiagostutz** [jairsjunior/go-ssh-client-tunnel#1]
Hi!
I'm using your lib on https://github.com/labbsr0x/convid-agent-windows but I wasn't able to handle erros in case of connection issues invoking the `CreateConnection*` funcs. 

How about returning error on this functions so it can have a more complete interface to be used at third parties?

**Comment by jairsjunior** [comment]
Thanks for use this mod!! =D
Awesome suggestion! I will implement this now.

**Comment by jairsjunior** [comment]
@tiagostutz implemented!
